---
- name: Read AWS Secret using lookup
  hosts: localhost
  connection: local

  vars:
    secret_data: >-
      {{
        lookup(
          'amazon.aws.aws_secret',
          'my-app-secret',
          region='us-east-1'
        ) | from_json
      }}

  tasks:
    - name: Print username
      ansible.builtin.debug:
        msg: "{{ secret_data.username }}"

    - name: Print password
      ansible.builtin.debug:
        msg: "{{ secret_data.password }}"
